### ISSUE TITLE
A bunch of files in hardware/cardiff/VMs directory make packaging very slow

### ISSUE THREAD

**Issue by amoralej** [redhat-cip/hardware#100]
Hi,

Building python-hardware in fedora is taking quite long (~20-30 mins). While investigating on it i've found that directory:

hardware/cardiff/VMs

contains ~ 77MB (+18000 files) of .hw files apparently containing data.

Are those files used/useful in the package or is it something that may be cleaned?

Best regards,

Alfredo

**Comment by dtantsur** [comment]
@ErwanAliasr1 do you remember?

**Comment by amoralej** [comment]
BTW, i think all those files were added in https://github.com/redhat-cip/hardware/commit/c4b0288913d611f8603161ad4f9c552eaf03df9c

**Comment by elfosardo** [comment]
@fredericlepied  can we remove those files ?

**Comment by ErwanAliasr1** [comment]
Yes please.

Le mer. 7 août 2019 à 19:04, Riccardo Pittau <notifications@github.com> a
écrit :
