### ISSUE TITLE
Adding Riccardo to collaborators?

### ISSUE THREAD

**Issue by dtantsur** [redhat-cip/hardware#104]
Hi folks!

This is a formal proposal to give Riccardo Pittau aka @elfosardo commit rights. Riccardo is one of the most active (probably the most active) contributors in terms of both code and review.

What do you think? @tbreeds @ErwanAliasr1?

**Comment by ErwanAliasr1** [comment]
I'm fine with it for sure.

Le ven. 9 août 2019 à 15:06, Dmitry Tantsur <notifications@github.com> a
écrit :

**Comment by tbreeds** [comment]
+1

Make it so!

How do we do that?

**Comment by dtantsur** [comment]
I think I've done it, now @elfosardo has to accept.

**Comment by elfosardo** [comment]
accepted! Thanks all, I really appreciate the trust :)
