### ISSUE TITLE
Drop Python 2.7 support

### ISSUE THREAD

**Issue by elfosardo** [redhat-cip/hardware#114]
The time has come!
Or, well, it's coming very soon!
https://pythonclock.org/

We should start considering, or better actively doing something, about dropping Python 2.7 support.
First step should be removing testing support, then refactoring the code to remove compatibility.
I believe testing can be dropped now or very early after beginning of next year (00:01 January 1st sounds like a great time and the perfect way to celebrate the start of 2020).
We can wait a bit longer for the compatibility break, just in case bugs need to be fixed, and can be done in multiple steps.

Thoughts?

**Comment by dtantsur** [comment]
I'm fine with that. I guess we should ask @ErwanAliasr1 as well.

**Comment by ErwanAliasr1** [comment]
Let's do it. No reason to keep 2.x

**Comment by elfosardo** [comment]
Well that's great!
I'll prepare a patch to remove testing for Python 2.x, but I'd like to leave another couple of days for people to comment, I'll push it on Monday.

**Comment by elfosardo** [comment]
First patch is out #116

**Comment by elfosardo** [comment]
Python 2.x is gone, long live Python 3.x !
