### ISSUE TITLE
Splitting hardware-cardiff into a new project?

### ISSUE THREAD

**Issue by dtantsur** [redhat-cip/hardware#124]
The cardfiff module brings two extremely heavy dependencies: numpy and pandas. At least on Red Hat systems, pandas ends up pulling X11 libraries. I've noticed that there are no cross-dependencies between hardware.cardiff and the rest of the library. What if we create a new project and move it there?

**Comment by dtantsur** [comment]
ping @ErwanAliasr1 as potentially the most interested in the cardiff part.

**Comment by ErwanAliasr1** [comment]
Honestly, this code is mostly unused, we could even drop it from the repo.
If need we'll resurect it from the removal commit.
I would +2 a removal commit

**Comment by tbreeds** [comment]
If we're not actively using it I'm okay with removing it.  If it's a mistake at that point we can create a new library or just undelete it.

**Comment by elfosardo** [comment]
considering that Erwan is ok with removing it and he's the author, I guess we're good with that :)

**Comment by oneswig** [comment]
Hi @dtantsur @ErwanAliasr1 we do use cardiff (admittedly not often) and value it, would you consider making it into a separate library or package on pypi?  Would appreciate it!

**Comment by ErwanAliasr1** [comment]
Do you really use it ? I felt it was almost abandoned by many and probably
buggy on some parts :/
Do you really feel it as useful ? Does it worth beeing saved ? :)

Le mar. 9 juin 2020 à 17:52, Stig Telfer <notifications@github.com> a
écrit :
