### ISSUE TITLE
`tox -epep8` fails since commit "a8d10ce detect: Fixing numa cpu_count computation"

### ISSUE THREAD

**Issue by sere** [redhat-cip/hardware#130]
Fails are E225 missing whitespace around operator, E303 too many blank lines and E501 line too long.

Should we include pep8 tests in the Travis CI test suite?

**Comment by elfosardo** [comment]
Thanks for reporting this @sere 
As you can see in the travis configuration file, we should be already running pep8 tests, but I double-checked and I can confirm that something's odd with that, my suspect is we're using the wrong variable to set the tox environment during the travis runs.
I'm testing it in #132

**Comment by elfosardo** [comment]
@sere this was fixed by #132 
thanks again!
