### ISSUE TITLE
Travis CI alternatives

### ISSUE THREAD

**Issue by elfosardo** [redhat-cip/hardware#165]
Travis team announced in [this post](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing) that their platform is changing model, and it will not be entirely free anymore.
They will still have a free tier that could be enough for this project, and they also announced [in another post](https://blog.travis-ci.com/oss-announcement) that open source testing will always be free, but we should still find alternatives, just in case.
For example Github actions can be used to run unit and linting tests for python, but we can explore other solutions as well.

**Comment by dtantsur** [comment]
If we switch at all, I think it should be to github actions since they're built-in.

**Comment by elfosardo** [comment]
@dtantsur I agree, I'll start having a look at that

**Comment by elfosardo** [comment]
The github actions look fine and are way faster than Travis.
I propose we just switch to them.

**Comment by elfosardo** [comment]
switch has happened, I've removed the webhooks
