### ISSUE TITLE
hardware-detect disk benchmark fails to parse modern fio output

### ISSUE THREAD

**Issue by priteau** [redhat-cip/hardware#187]
The output of `fio` parsed by the disk benchmark has changed around 2017: https://github.com/axboe/fio/commit/d694a6a7c02f577b2bb5d0ad24331b775acf6869

The disk benchmark code in `hardware-detect` fails to parse its output.

**Comment by priteau** [comment]
@elfosardo Please note that we have a fix in progress, pull request coming soon.

**Comment by elfosardo** [comment]
@priteau feel free to assign this to yourself or the fix owner
