### ISSUE TITLE
Improving the output...

### ISSUE THREAD

**Issue by alexmyczko** [redhat-cip/hardware#195]
Meanwhile, I can run `apt install python3-hardware` and then `hardware-detect --human` but the output

comes with a few error messages that could be easily catched:

```
/bin/sh: 1: cli64: not found
Info: No Areca controller found
Cannot find megacli on the system
read_smart: Reading S.M.A.R.T information on /dev/sdb
read_smart: Reading S.M.A.R.T information on /dev/sdb with -d ata
read_smart: no device /dev/sdb
read_smart: Reading S.M.A.R.T information on /dev/sda
read_smart: Reading S.M.A.R.T information on /dev/sda with -d ata
read_smart: no device /dev/sda
modprobe: FATAL: Module ipmi_smb not found in directory /lib/modules/6.1.0-5-amd64
Info: Probing ipmi_si failed
Info: Probing ipmi_devintf failed
IANA PEN registry open failed: No such file or directory
Info: No Infiniband device found
IANA PEN registry open failed: No such file or directory
/bin/sh: 1: Syntax error: end of file unexpected
Unable to run hp-conrep: 
[('hpa', 'slots', 'count', '2'),
```

The one with cli64: not found, Syntax error?, Unable to run...

**Comment by elfosardo** [comment]
@alexmyczko thanks, I was planning to fix that and some other but never get to it and forgot!

**Comment by alexmyczko** [comment]
@elfosardo checking if a binary to manage a raid controller, isn't truly the check if the raid controller is in, is it? wouldn't checking the `lspci` output be better for that? AND checking for the binary to be able to managed the raid controller hardware? what is also pretty cumbersome is getting all the raid controller hardware binaries (as they're all binary only, and distributed in very interesteing ways, sometimes)
