### ISSUE TITLE
Publish new release with python3 support

### ISSUE THREAD

**Issue by amoralej** [redhat-cip/hardware#78]
In fedora, it's requested to build python3 versions however latest release 0.18 does not support it. I've seen some commits related to python3, could we get a new release which supports it?

**Comment by tbreeds** [comment]
So you just need the current HEAD released?  I thought there were changes needed to support py3+

**Comment by elfosardo** [comment]
@tbreeds some changes were recently applied to get full support for python3, we've added tox unit tests coverage for python 3.6 and 3.7, I checked the syntax of the modules using ast and the code itself builds using python 3.6.
We're still lacking an automated CI and actual test coverage is not the best, also I had the chance to test part of scripts on actual hardware, but it would be awesome if we could have full cover on that as well.
From my perspective this should be ready to be used with python3, of course having more opinions would be better :)

**Comment by tbreeds** [comment]
Done.

Hopefully OpenStack and RDO should just pick up this release
