### ISSUE TITLE
Splitting output by parts

### ISSUE THREAD

**Issue by ErwanAliasr1** [redhat-cip/hardware#90]
I'm in a process of using the output of python hardware to manage a 50K server farm.
One of the feature I'll need is to be able to split the output per parts to ease the conformity checking from the installed part vs a list of possible parts (initial + remplacement parts).
The  current output is a single file, I'm wondering if we could output each component in a separate file but keep a single one for compat.

Any thoughts on this ?

**Comment by ErwanAliasr1** [comment]
Poke @tbreeds @elfosardo

**Comment by tbreeds** [comment]
Yup I;m fine with splitting things and/or adding a very simple 'query' language to the CLI

`hardware-dectect --storage|--cpu etc`

As long as we by default we're backwards compatible until we switch to 1.x then we can switch to separate streams by default

**Comment by elfosardo** [comment]
I'm also fine with splitting things, I think it's the correct direction to improve modularity of the code.
Maybe this change #89 can be a good base to start reshaping things in that direction.

**Comment by ErwanAliasr1** [comment]
I'd be also interested to understand how Redhat is still using this part in the products.
I'm considering also on my use case to rework the matching code (from edeploy) and wonder if you have some needs here.

**Comment by elfosardo** [comment]
@ErwanAliasr1 more in general the python-hardware package is used by Openstack Ironic, specifically by Ironic Python Agent, to get extra details and information on the hardware present in a host.
You can find more info here:
https://docs.openstack.org/ironic-python-agent/latest/

**Comment by ErwanAliasr1** [comment]
@elfosardo yeah I remember that part but was more likely wondering if you were using the matching code/principle.
I'm still puzzled why there is no contribution on the detection code itself. It misses tools or updates. If no one see that I really wonder if that is used or not by real people behind.

**Comment by tbreeds** [comment]
I started poking at hardware because the detection stuff for ppc64le was broken for my use case.  So I think no contribution means it's "good enough".

I'm currently working on an ansible module that will use the smallest part of hardware (system UUID detection) but it'll save duplicating code and reduce a bunch of copy-n-paste

**Comment by elfosardo** [comment]
this is slowly moving forward with moving the different detect code to various modules
the final goal is to simplify the detect script and add options to run all, multiple or single detect commands for the different parts

**Comment by elfosardo** [comment]
this was completed
